# Começando no Pandas

https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html

# Bases de dados

www.kaggle.com

# Dataset Pokémon

Baixe <a href="https://www.kaggle.com/cristobalmitchell/pokedex">aqui</a>. (consulte sempre no kaggle por novas bases)

In [1]:
import pandas as pd
import numpy as np

In [7]:
#abrir um csv novo
pokemon_df = pd.read_csv("pokemon.csv")

pokemon_df.sample(3)

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
233,234,II,Stantler,Odoshishi,normal,NaN,Big Horn Pokémon,50,50,1.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stantler’s magnificent antlers were traded at ...
62,63,I,Abra,Casey,psychic,NaN,Psi Pokémon,75.49,24.51,0.9,...,Level,Kadabra,Trade,Alakazam,NaN,NaN,NaN,NaN,NaN,This Pokémon uses its psychic powers while it ...
582,583,V,Vanillish,Vanirich,ice,NaN,Icy Snow Pokémon,50.2,49.8,1.1,...,Level,Vanillish,Level,Vanilluxe,NaN,NaN,NaN,NaN,NaN,"By drinking pure water, it grows its icy body...."

# Resumo estatístico do dataframe

In [8]:
#resumo de informações sobre os campos do dataframe
pokemon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 55 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   national_number     898 non-null    int64
 1   gen                 898 non-null    object
 2   english_name        898 non-null    object
 3   japanese_name       898 non-null    object
 4   primary_type        898 non-null    object
 5   secondary_type      469 non-null    object
 6   classification      898 non-null    object
 7   percent_male        776 non-null    object
 8   percent_female      776 non-null    object
 9   height_m            898 non-null    float64
 10  weight_kg           898 non-null    float64
 11  capture_rate        898 non-null    object
 12  base_egg_steps      898 non-null    int64
 13  hp                  898 non-null    int64
 14  attack              898 non-null    int64
 15  defense             898 non-null    int64
 16  sp_attack           898 non-null    int64
 17  sp_defense          898 non-null    int64
 18  speed               898 non-null    int64
 19  abilities_0         898 non-null    object
 20  abilities_1         495 non-null    object
 21  abilities_2         3 non-null      object
 22  abilities_hidden    763 non-null    object
 23  against_normal      898 non-null    float64
 24  against_fire        898 non-null    float64
 25  against_water       898 non-null    float64
 26  against_electric    898 non-null    float64
 27  against_grass       898 non-null    float64
 28  against_ice         898 non-null    float64
 29  against_fighting    898 non-null    float64
 30  against_poison      898 non-null    float64
 31  against_ground      898 non-null    float64
 32  against_flying      898 non-null    float64
 33  against_psychict    898 non-null    float64
 34  against_bug         898 non-null    float64
 35  against_rock        898 non-null    float64
 36  against_ghost       898 non-null    float64
 37  against_dragon      898 non-null    float64
 38  against_dark        898 non-null    float64
 39  against_steel       898 non-null    float64
 40  against_fairy       898 non-null    float64
 41  is_sublegendary     898 non-null    int64
 42  is_legendary        898 non-null    int64
 43  is_mythical         898 non-null    int64
 44  evochain_0          898 non-null    object
 45  evochain_1          728 non-null    object
 46  evochain_2          728 non-null    object
 47  evochain_3          335 non-null    object
 48  evochain_4          332 non-null    object
 49  evochain_5          19 non-null     object
 50  evochain_6          19 non-null     object
 51  gigantamax          31 non-null     object
 52  mega_evolution      46 non-null     object
 53  mega_evolution_alt  2 non-null      object
 54  description         898 non-null    object
dtypes: float64(20), int64(11), object(24)
memory usage: 386.0+ KB

In [9]:
#resumo de informações estatísticas importantes
pokemon_df.describe()

,national_number,height_m,weight_kg,base_egg_steps,hp,attack,defense,sp_attack,sp_defense,speed,...,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,is_sublegendary,is_legendary,is_mythical
count,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,...,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.00000,898.000000,898.000000,898.000000
mean,449.500000,1.185969,63.970045,7544.587973,69.031180,76.544543,71.886414,69.681514,69.876392,65.949889,...,0.999165,1.245546,0.994432,0.972717,1.057628,0.984131,1.08157,0.050111,0.022272,0.022272
std,259.374568,1.234222,119.430298,7101.313608,26.213707,29.665559,29.536184,29.372609,27.012142,28.456596,...,0.609120,0.702248,0.553163,0.365120,0.441639,0.497022,0.53157,0.218296,0.147648,0.147648
min,1.000000,0.100000,0.100000,1280.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,...,0.250000,0.250000,0.000000,0.000000,0.250000,0.250000,0.25000,0.000000,0.000000,0.000000
25%,225.250000,0.500000,8.500000,5120.000000,50.000000,55.000000,50.000000,46.250000,50.000000,45.000000,...,0.500000,1.000000,1.000000,1.000000,1.000000,0.500000,1.00000,0.000000,0.000000,0.000000
50%,449.500000,1.000000,27.000000,5120.000000,65.000000,75.000000,67.000000,65.000000,65.000000,65.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,0.000000,0.000000,0.000000
75%,673.750000,1.500000,65.000000,6400.000000,80.000000,95.000000,90.000000,90.000000,85.000000,85.000000,...,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.00000,0.000000,0.000000,0.000000
max,898.000000,20.000000,999.900000,30720.000000,255.000000,181.000000,230.000000,173.000000,230.000000,200.000000,...,4.000000,4.000000,4.000000,2.000000,4.000000,4.000000,4.00000,1.000000,1.000000,1.000000

In [12]:
linhas, colunas = pokemon_df.shape #linhas e colunas (campos)

print("Linhas:", linhas)
print("Colunas:", colunas)

Linhas: 898
Colunas: 55

# Selecionar subconjuntos do Dataframe

In [15]:
coluna_tipo = pokemon_df["primary_type"] #selecionar uma coluna específica (tipo series, um array unidimensional)

type(coluna_tipo)

pandas.core.series.Series

In [18]:
coluna_tipo.tail()

893    electric
894      dragon
895         ice
896       ghost
897     psychic
Name: primary_type, dtype: object

In [23]:
#e se eu quiser o tipo com o nome junto?
name_type_df = pokemon_df[["english_name", "primary_type", "secondary_type"]]

name_type_df.sample(5)

    english_name primary_type secondary_type
774       Komala       normal            NaN
509      Liepard         dark            NaN
597   Ferrothorn        grass          steel
169     Chinchou        water       electric
142      Snorlax       normal            NaN

In [24]:
type(name_type_df)

pandas.core.frame.DataFrame

In [27]:
#filtrar pokémon do tipo grama
grass_df = pokemon_df[pokemon_df["primary_type"] == 'grass']

grass_df.head()

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
0,1,I,Bulbasaur,Fushigidane,grass,poison,Seed Pokémon,88.14,11.86,0.7,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,There is a plant seed on its back right from t...
1,2,I,Ivysaur,Fushigisou,grass,poison,Seed Pokémon,88.14,11.86,1.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,"When the bulb on its back grows large, it appe..."
2,3,I,Venusaur,Fushigibana,grass,poison,Seed Pokémon,88.14,11.86,2.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,Gigantamax Venusaur,Mega Venusaur,NaN,Its plant blooms when it is absorbing solar en...
42,43,I,Oddish,Nazonokusa,grass,poison,Weed Pokémon,50.2,49.8,0.5,...,Level,Gloom,Use Leaf Stone,Vileplume,Use Sun Stone,Bellossom,NaN,NaN,NaN,"If exposed to moonlight, it starts to move. It..."
43,44,I,Gloom,Kusaihana,grass,poison,Weed Pokémon,50.2,49.8,0.8,...,Level,Gloom,Use Leaf Stone,Vileplume,Use Sun Stone,Bellossom,NaN,NaN,NaN,Its pistils exude an incredibly foul odor. The...

In [31]:
#filtrar pokémon fraco contra tipo água
weak_against_water_df = pokemon_df[pokemon_df["against_water"] > 2]

weak_against_water_df[["english_name", "primary_type", "against_water"]]

    english_name primary_type  against_water
73       Geodude         rock            4.0
74      Graveler         rock            4.0
75         Golem         rock            4.0
94          Onix         rock            4.0
110      Rhyhorn       ground            4.0
111       Rhydon       ground            4.0
218     Magcargo         fire            4.0
245     Larvitar         rock            4.0
246      Pupitar         rock            4.0
321        Numel         fire            4.0
322     Camerupt         fire            4.0
463    Rhyperior       ground            4.0
837       Carkol         rock            4.0
838    Coalossal         rock            4.0

In [35]:
#filtrar pokémon fraco contra tipo água e terra ao mesmo tempo
weak_against_water_ground_df = pokemon_df[(pokemon_df["against_water"] > 1) & (pokemon_df["against_ground"] > 1)]

weak_against_water_ground_df[["english_name", "primary_type", "against_water", "against_ground"]]

    english_name primary_type  against_water  against_ground
3     Charmander         fire            2.0             2.0
4     Charmeleon         fire            2.0             2.0
30     Nidoqueen       poison            2.0             2.0
33      Nidoking       poison            2.0             2.0
36        Vulpix         fire            2.0             2.0
..           ...          ...            ...             ...
814    Cinderace         fire            2.0             2.0
836     Rolycoly         rock            2.0             2.0
837       Carkol         rock            4.0             4.0
838    Coalossal         rock            4.0             4.0
873  Stonjourner         rock            2.0             2.0

[101 rows x 4 columns]

In [38]:
#retornar pokémon com megaevolução
mega_df = pokemon_df[pokemon_df["mega_evolution"].notna()]

mega_df

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
2,3,I,Venusaur,Fushigibana,grass,poison,Seed Pokémon,88.14,11.86,2.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,Gigantamax Venusaur,Mega Venusaur,NaN,Its plant blooms when it is absorbing solar en...
5,6,I,Charizard,Lizardon,fire,flying,Flame Pokémon,88.14,11.86,1.7,...,Level,Charmeleon,Level,Charizard,NaN,NaN,Gigantamax Charizard,Mega Charizard X,Mega Charizard Y,It spits fire that is hot enough to melt bould...
8,9,I,Blastoise,Kamex,water,NaN,Shellfish Pokémon,88.14,11.86,1.6,...,Level,Wartortle,Level,Blastoise,NaN,NaN,Gigantamax Blastoise,Mega Blastoise,NaN,It crushes its foe under its heavy body to cau...
14,15,I,Beedrill,Spear,bug,poison,Poison Bee Pokémon,50,50,1.0,...,Level,Kakuna,Level,Beedrill,NaN,NaN,NaN,Mega Beedrill,NaN,It has three poisonous stingers on its foreleg...
17,18,I,Pidgeot,Pigeot,normal,flying,Bird Pokémon,50,50,1.5,...,Level,Pidgeotto,Level,Pidgeot,NaN,NaN,NaN,Mega Pidgeot,NaN,"This Pokémon flies at Mach 2 speed, seeking pr..."
64,65,I,Alakazam,Foodin,psychic,NaN,Psi Pokémon,75.49,24.51,1.5,...,Level,Kadabra,Trade,Alakazam,NaN,NaN,NaN,Mega Alakazam,NaN,It has an incredibly high level of intelligenc...
79,80,I,Slowbro,Yadoran,water,psychic,Hermit Crab Pokémon,50.2,49.8,1.6,...,Level,Slowbro,Trade with King's Rock,Slowking,Slowpoke,Use Galarica Cuff,NaN,Mega Slowbro,NaN,Slowpoke became Slowbro when a Shellder bit on...
93,94,I,Gengar,Gangar,ghost,poison,Shadow Pokémon,50.2,49.8,1.5,...,Level,Haunter,Trade,Gengar,NaN,NaN,Gigantamax Gengar,Mega Gengar,NaN,"On the night of a full moon, if shadows move o..."
114,115,I,Kangaskhan,Garura,normal,NaN,Parent Pokémon,0,100,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Kangaskhan,NaN,Although it’s carrying its baby in a pouch on ...
126,127,I,Pinsir,Kailios,bug,NaN,Stagbeetle Pokémon,50.2,49.8,1.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Pinsir,NaN,These Pokémon judge one another based on pince...
129,130,I,Gyarados,Gyarados,water,flying,Atrocious Pokémon,50.2,49.8,6.5,...,Level,Gyarados,NaN,NaN,NaN,NaN,NaN,Mega Gyarados,NaN,It has an extremely aggressive nature. The Hyp...
141,142,I,Aerodactyl,Ptera,rock,flying,Fossil Pokémon,88.14,11.86,1.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Aerodactyl,NaN,This is a ferocious Pokémon from ancient times...
149,150,I,Mewtwo,Mewtwo,psychic,NaN,Genetic Pokémon,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Mewtwo X,Mega Mewtwo Y,"Its DNA is almost the same as Mew’s. However, ..."
180,181,II,Ampharos,Denryu,electric,NaN,Light Pokémon,50,50,1.4,...,Level,Flaaffy,Level,Ampharos,NaN,NaN,NaN,Mega Ampharos,NaN,The light from its tail can be seen from space...
207,208,II,Steelix,Haganeil,steel,ground,Iron Snake Pokémon,50.2,49.8,9.2,...,Trade with Metal Coat,Steelix,NaN,NaN,NaN,NaN,NaN,Mega Steelix,NaN,It is said that if an Onix lives for over 100 ...
211,212,II,Scizor,Hassam,bug,steel,Pincer Pokémon,50.2,49.8,1.8,...,Trade with Metal Coat,Scizor,NaN,NaN,NaN,NaN,NaN,Mega Scizor,NaN,Bulky pincers account for one third of Scizor’...
213,214,II,Heracross,Heracros,bug,fighting,Singlehorn Pokémon,50.2,49.8,1.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Heracross,NaN,Heracross loves sweet sap and will go looking ...
228,229,II,Houndoom,Hellgar,dark,fire,Dark Pokémon,50,50,1.4,...,Level,Houndoom,NaN,NaN,NaN,NaN,NaN,Mega Houndoom,NaN,They spew flames mixed with poison to finish o...
247,248,II,Tyranitar,Bangiras,rock,dark,Armor Pokémon,50.2,49.8,2.0,...,Level,Pupitar,Level,Tyranitar,NaN,NaN,NaN,Mega Tyranitar,NaN,Its body can’t be harmed by any sort of attack...
253,254,III,Sceptile,Jukain,grass,NaN,Forest Pokémon,88.14,11.86,1.7,...,Level,Grovyle,Level,Sceptile,NaN,NaN,NaN,Mega Sceptile,NaN,The leaves growing on Sceptile’s body are very...
256,257,III,Blaziken,Bursyamo,fire,fighting,Blaze Pokémon,88.14,11.86,1.9,...,Level,Combusken,Level,Blaziken,NaN,NaN,NaN,Mega Blaziken,NaN,"In battle, Blaziken blows out intense flames f..."
259,260,III,Swampert,Laglarge,water,ground,Mud Fish Pokémon,88.14,11.86,1.5,...,Level,Marshtomp,Level,Swampert,NaN,NaN,NaN,Mega Swampert,NaN,Swampert is very strong. It has enough power t...
281,282,III,Gardevoir,Sirnight,psychic,fairy,Embrace Pokémon,50.2,49.8,1.6,...,Level,Kirlia,Level,Gardevoir,NaN,NaN,NaN,Mega Gardevoir,NaN,It has the power to predict the future. Its po...
301,302,III,Sableye,Yamirami,dark,ghost,Darkness Pokémon,50.2,49.8,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Sableye,NaN,This Pokémon is feared. When its gemstone eyes...
302,303,III,Mawile,Kucheat,steel,fairy,Deceiver Pokémon,50.2,49.8,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Mawile,NaN,It uses its docile-looking face to lull foes i...
305,306,III,Aggron,Bossgodora,steel,rock,Iron Armor Pokémon,50.2,49.8,2.1,...,Level,Lairon,Level,Aggron,NaN,NaN,NaN,Mega Aggron,NaN,Aggron has a horn sharp enough to perforate th...
307,308,III,Medicham,Charem,fighting,psychic,Meditate Pokémon,50,50,1.3,...,Level,Medicham,NaN,NaN,NaN,NaN,NaN,Mega Medicham,NaN,"It is said that through meditation, Medicham h..."
309,310,III,Manectric,Livolt,electric,NaN,Discharge Pokémon,50.2,49.8,1.5,...,Level,Manectric,NaN,NaN,NaN,NaN,NaN,Mega Manectric,NaN,It stimulates its own muscles with electricity...
318,319,III,Sharpedo,Samehader,water,dark,Brutal Pokémon,50.2,49.8,1.8,...,Level,Sharpedo,NaN,NaN,NaN,NaN,NaN,Mega Sharpedo,NaN,"As soon as it catches the scent of prey, Sharp..."
322,323,III,Camerupt,Bakuuda,fire,ground,Eruption Pokémon,50,50,1.9,...,Level,Camerupt,NaN,NaN,NaN,NaN,NaN,Mega Camerupt,NaN,Camerupt has a volcano inside its body. Magma ...
333,334,III,Altaria,Tyltalis,dragon,flying,Humming Pokémon,50.2,49.8,1.1,...,Level,Altaria,NaN,NaN,NaN,NaN,NaN,Mega Altaria,NaN,"As it flies in a calm and relaxed manner, Alta..."
353,354,III,Banette,Juppeta,ghost,NaN,Marionette Pokémon,50,50,1.1,...,Level,Banette,NaN,NaN,NaN,NaN,NaN,Mega Banette,NaN,It’s a stuffed toy that was thrown away and be...
358,359,III,Absol,Absol,dark,NaN,Disaster Pokémon,50.2,49.8,1.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Absol,NaN,"Swift as the wind, Absol races through fields ..."
361,362,III,Glalie,Onigohri,ice,NaN,Face Pokémon,50.2,49.8,1.5,...,Level,Glalie,"On Female Pokémon, use Dawn Stone",Froslass,NaN,NaN,NaN,Mega Glalie,NaN,"It has a body of ice that won’t melt, even wit..."
372,373,III,Salamence,Bohmander,dragon,flying,Dragon Pokémon,50.2,49.8,1.5,...,Level,Shelgon,Level,Salamence,NaN,NaN,NaN,Mega Salamence,NaN,Salamence is an unusual Pokémon in that it was...
375,376,III,Metagross,Metagross,steel,psychic,Iron Leg Pokémon,NaN,NaN,1.6,...,Level,Metang,Level,Metagross,NaN,NaN,NaN,Mega Metagross,NaN,Because the magnetic powers of these Pokémon g...
379,380,III,Latias,Latias,dragon,psychic,Eon Pokémon,0,100,1.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Latias,NaN,Latias is highly sensitive to the emotions of ...
380,381,III,Latios,Latios,dragon,psychic,Eon Pokémon,100,0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Latios,NaN,Latios has the ability to make others see an i...
383,384,III,Rayquaza,Rayquaza,dragon,flying,Sky High Pokémon,NaN,NaN,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Rayquaza,NaN,Rayquaza is said to have lived for hundreds of...
427,428,IV,Lopunny,Mimilop,normal,NaN,Rabbit Pokémon,50.2,49.8,1.2,...,Level Up with Happiness Value at 220,Lopunny,NaN,NaN,NaN,NaN,NaN,Mega Lopunny,NaN,Lopunny is constantly monitoring its surroundi...
444,445,IV,Garchomp,Gaburias,dragon,ground,Mach Pokémon,50.2,49.8,1.9,...,Level,Gabite,Level,Garchomp,NaN,NaN,NaN,Mega Garchomp,NaN,Garchomp makes its home in volcanic mountains....
447,448,IV,Lucario,Lucario,fighting,steel,Aura Pokémon,88.14,11.86,1.2,...,Level Up with Happiness Value at 220 During th...,Lucario,NaN,NaN,NaN,NaN,NaN,Mega Lucario,NaN,"It controls waves known as auras, which are po..."
459,460,IV,Abomasnow,Yukinooh,grass,ice,Frosted Tree Pokémon,50.2,49.8,2.2,...,Level,Abomasnow,NaN,NaN,NaN,NaN,NaN,Mega Abomasnow,NaN,If it sees any packs of Darumaka going after S...
474,475,IV,Gallade,Erureido,psychic,fighting,Blade Pokémon,100,0,1.6,...,Level,Kirlia,"On Male Pokémon, use Dawn Stone",Gallade,NaN,NaN,NaN,Mega Gallade,NaN,"True to its honorable-warrior image, it uses t..."
530,531,V,Audino,Tabunne,normal,NaN,Hearing Pokémon,50.2,49.8,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Audino,NaN,Audino’s sense of hearing is superb. Not even ...
718,719,VI,Diancie,Diancie,rock,fairy,Jewel Pokémon,NaN,NaN,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mega Diancie,NaN,"A sudden transformation of Carbink, its pink, ..."

In [49]:
#iloc: acessar por índice
pokemon_df.iloc[5:15:2]

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
5,6,I,Charizard,Lizardon,fire,flying,Flame Pokémon,88.14,11.86,1.7,...,Level,Charmeleon,Level,Charizard,NaN,NaN,Gigantamax Charizard,Mega Charizard X,Mega Charizard Y,It spits fire that is hot enough to melt bould...
7,8,I,Wartortle,Kameil,water,NaN,Turtle Pokémon,88.14,11.86,1.0,...,Level,Wartortle,Level,Blastoise,NaN,NaN,NaN,NaN,NaN,It is recognized as a symbol of longevity. If ...
9,10,I,Caterpie,Caterpie,bug,NaN,Worm Pokémon,50.2,49.8,0.3,...,Level,Metapod,Level,Butterfree,NaN,NaN,NaN,NaN,NaN,"For protection, it releases a horrible stench ..."
11,12,I,Butterfree,Butterfree,bug,flying,Butterfly Pokémon,50.2,49.8,1.1,...,Level,Metapod,Level,Butterfree,NaN,NaN,Gigantamax Butterfree,NaN,NaN,"In battle, it flaps its wings at great speed t..."
13,14,I,Kakuna,Cocoon,bug,poison,Cocoon Pokémon,50,50,0.6,...,Level,Kakuna,Level,Beedrill,NaN,NaN,NaN,NaN,NaN,"Able to move only slightly. When endangered, i..."

In [68]:
pokemon_df.loc[:, "english_name"]

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
893     Regieleki
894     Regidrago
895     Glastrier
896     Spectrier
897       Calyrex
Name: english_name, Length: 898, dtype: object